[project]
name = "browser-use-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "win2333", email = "win2333@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "browser-use>=0.12.2",
]

[project.scripts]
browser-use-test = "browser_use_test:main"

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"
